In [ ]:
import numpy as np
import cvxpy as cp

In [ ]:
# set the seed for the random number generator
# DO NOT CHANGE THE SEED!
np.random.seed(2) 


### Data for the pizza problem

L = 20
c = np.ceil(10*np.random.rand(L))
n = 2 # This is only used in Problem 1 part (b)

D = 25
p = np.ceil(100*np.random.rand(D))
# A location i is acceptable for dorm j is S[j,i] = 1
S = np.random.randint(2,size=(D,L))

In [ ]:
#1 a
#x=1 means that we will open a restaurant at place i
#the constraints mean that at every place, students can have at least one restaurant to go
x = cp.Variable(L,boolean=True)

obj = cp.Minimize(c*x)

constraints = [
    np.sum(S[0]*x)>=1,
    np.sum(S[1]*x)>=1,
    np.sum(S[2]*x)>=1,
    np.sum(S[3]*x)>=1,
    np.sum(S[4]*x)>=1,
    np.sum(S[5]*x)>=1,
    np.sum(S[6]*x)>=1,
    np.sum(S[7]*x)>=1,
    np.sum(S[8]*x)>=1,
    np.sum(S[9]*x)>=1,
    np.sum(S[10]*x)>=1,
    np.sum(S[11]*x)>=1,
    np.sum(S[12]*x)>=1,
    np.sum(S[13]*x)>=1,
    np.sum(S[14]*x)>=1,
    np.sum(S[15]*x)>=1,
    np.sum(S[16]*x)>=1,
    np.sum(S[17]*x)>=1,
    np.sum(S[18]*x)>=1,
    np.sum(S[19]*x)>=1,
    np.sum(S[20]*x)>=1,
    np.sum(S[21]*x)>=1,
    np.sum(S[22]*x)>=1,
    np.sum(S[23]*x)>=1,
    np.sum(S[24]*x)>=1
]

prob = cp.Problem(obj,constraints)

prob.solve()
if (prob.status == 'optimal'):
    print('value = ' + str(prob.value))
    print('x = ' + str(x.value))

value = 7.0
x = [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [ ]:
#1 b
#y=1 means that we will keep the dorm, and the left side of the constraints mean that if people can go to the restaurant, the sum must >=1, else =0
y = cp.Variable(D,boolean=True)

obj = cp.Maximize(cp.sum(p*y))

constraints = [
    cp.sum(x)<=n,
    cp.sum(S[0]*x)>=y[0],
    cp.sum(S[1]*x)>=y[1],
    cp.sum(S[2]*x)>=y[2],
    cp.sum(S[3]*x)>=y[3],
    cp.sum(S[4]*x)>=y[4],
    cp.sum(S[5]*x)>=y[5],
    cp.sum(S[6]*x)>=y[6],
    cp.sum(S[7]*x)>=y[7],
    cp.sum(S[8]*x)>=y[8],
    cp.sum(S[9]*x)>=y[9],
    cp.sum(S[10]*x)>=y[10],
    cp.sum(S[11]*x)>=y[11],
    cp.sum(S[12]*x)>=y[12],
    cp.sum(S[13]*x)>=y[13],
    cp.sum(S[14]*x)>=y[14],
    cp.sum(S[15]*x)>=y[15],
    cp.sum(S[16]*x)>=y[16],
    cp.sum(S[17]*x)>=y[17],
    cp.sum(S[18]*x)>=y[18],
    cp.sum(S[19]*x)>=y[19],
    cp.sum(S[20]*x)>=y[20],
    cp.sum(S[21]*x)>=y[21],
    cp.sum(S[22]*x)>=y[22],
    cp.sum(S[23]*x)>=y[23],
    cp.sum(S[24]*x)>=y[24]

]
prob = cp.Problem(obj,constraints)
prob.solve(solver = cp.GLPK_MI)
if (prob.status == 'optimal'):
    print('value = ' + str(prob.value))
    print('x = ' + str(x.value))
    print('y = ' + str(y.value))


value = 1039.0
x = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
y = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]


In [ ]:
## Data for Problem 2
#x means that the portfolio we have at last
#change means that if we change the portfolio of the stock, change=1,else change=0

b = np.array([0.12,0.15,0.13,0.10,0.20,0.10,0.12,0.08])
v = np.array([0.02,0.05,0.25,0.06,0.18,0.10,0.22,0.12])
K = 3

x = cp.Variable(8)
change = cp.Variable(8,boolean=True)

obj = cp.Minimize(cp.sum(cp.abs(x-v)))

constraints = [
    cp.sum(x)==1,
    cp.sum(change)<=K,
    x>=0,
    change>=x-b,
    change>=-(x-b)
    
]

prob = cp.Problem(obj,constraints)

prob.solve()
if (prob.status == 'optimal'):
    print('value = ' + str(prob.value))
    print('x = ' + str(x.value))
    print('change = ' + str(change.value))

value = 0.28000000000000014
x = [0.12 0.05 0.25 0.1  0.18 0.1  0.12 0.08]
change = [0. 1. 1. 0. 1. 0. 0. 0.]


In [ ]:
## Data for Problem 3

# set the seed for the random number generator
# DO NOT CHANGE THE SEED!
np.random.seed(15) 

n = 10

v = np.ceil(10*np.random.rand(n))
b = np.ceil(10*(np.random.rand(n,n)-np.random.rand(n,n)))
w = np.ceil(10*np.random.rand(n))
W = np.ceil(0.75*sum(w))

#the reason why we use z is that in cvxpy we can not use x*x, so we set a new variable and let z[i][j]=x[i]*x[j]
#the reason we set q=b.diagonal() is that we can transform this QKP problem to another IP problem
z = cp.Variable((n,n),boolean=True)
q = b.diagonal()
x = cp.Variable(n,boolean=True)

obj = cp.Maximize(v@x+cp.sum(b*z)+cp.sum(q*x))

constraints = [
  w@x <= W, 
  #∑w[i]*z[i][j]<=(W-w[i])*x[j]
  w*z[:,0:1]-w[0]*x[0]<=(W-w[0])*x[0],
  w*z[:,1:2]-w[1]*x[1]<=(W-w[1])*x[1],
  w*z[:,2:3]-w[2]*x[2]<=(W-w[2])*x[2],
  w*z[:,3:4]-w[3]*x[3]<=(W-w[3])*x[3],                  
  w*z[:,4:5]-w[4]*x[4]<=(W-w[4])*x[4],                                 
  w*z[:,5:6]-w[5]*x[5]<=(W-w[5])*x[5],
  w*z[:,6:7]-w[6]*x[6]<=(W-w[6])*x[6],
  w*z[:,7:8]-w[7]*x[7]<=(W-w[7])*x[7],
  w*z[:,8:9]-w[8]*x[8]<=(W-w[8])*x[8],
  w*z[:,9:10]-w[9]*x[9]<=(W-w[9])*x[9],
  #0<=z[i][j]<=x[j]<=1,i!=j
  z[1:10,0:1]<=x[0],
  z[0:1,1:2]<=x[1],z[2:10,1:2]<=x[1],
  z[0:2,2:3]<=x[2],z[3:10,2:3]<=x[2],
  z[0:3,3:4]<=x[3],z[4:10,3:4]<=x[3],
  z[0:4,4:5]<=x[4],z[5:10,4:5]<=x[4],
  z[0:5,5:6]<=x[5],z[6:10,5:6]<=x[5],
  z[0:6,6:7]<=x[6],z[7:10,6:7]<=x[6],
  z[0:7,7:8]<=x[7],z[8:10,7:8]<=x[7],
  z[0:8,8:9]<=x[8],z[9:10,8:9]<=x[8],
  z[0:9,9:10]<=x[9],
  #z[0]==cp.transforms(z[:,0:1]) 
  #z[i][j]=z[j][i]
  z[0][1]==z[1][0],z[0][2]==z[2][0],z[0][3]==z[3][0],z[0][4]==z[4][0],z[0][5]==z[5][0],z[0][6]==z[6][0],z[0][7]==z[7][0],z[0][8]==z[8][0],z[0][9]==z[9][0],
  z[1][2]==z[2][1],z[1][3]==z[3][1],z[1][4]==z[4][1],z[1][5]==z[5][1],z[1][6]==z[6][1],z[1][7]==z[7][1],z[1][8]==z[8][1],z[1][9]==z[9][1],
  z[2][3]==z[3][2],z[2][4]==z[4][2],z[2][5]==z[5][2],z[2][6]==z[6][2],z[2][7]==z[7][2],z[2][8]==z[8][2],z[2][9]==z[9][2],
  z[3][4]==z[4][3],z[3][5]==z[5][3],z[3][6]==z[6][3],z[3][7]==z[7][3],z[3][8]==z[8][3],z[3][9]==z[9][3],
  z[4][5]==z[5][4],z[4][6]==z[6][4],z[4][7]==z[7][4],z[4][8]==z[8][4],z[4][9]==z[9][4],
  z[5][6]==z[6][5],z[5][7]==z[7][5],z[5][8]==z[8][5],z[5][9]==z[9][5],
  z[6][7]==z[7][6],z[6][8]==z[8][6],z[6][9]==z[9][6], 
  z[7][8]==z[8][7],z[7][9]==z[9][7],   
  z[8][9]==z[9][8],                                                                        
               ]
int_prob = cp.Problem(obj,constraints) 
int_prob.solve()

if (int_prob.status == "optimal"):
    print('int_prob = ' + str(int_prob.value))
    print('x = ' + str(x.value))
    print('z = ' + str(z.value))

int_prob = 527.0
x = [1. 1. 1. 1. 1. 1. 0. 1. 1. 0.]
z = [[1. 0. 1. 1. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0. 1. 0. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 1. 0. 1. 1. 0.]
 [1. 0. 1. 1. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1. 1. 0. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
## Data for Problem 3

# set the seed for the random number generator
# DO NOT CHANGE THE SEED!
import numpy as np
import cvxpy as cp

np.random.seed(15) 

n = 10

v = np.ceil(10*np.random.rand(n))
b = np.ceil(10*(np.random.rand(n,n)-np.random.rand(n,n)))
w = np.ceil(10*np.random.rand(n))
W = np.ceil(0.75*sum(w))

#the reason why we use z is that in cvxpy we can not use x*x, so we set a new variable and let z[i][j]=x[i]*x[j]
#the reason we set q=b.diagonal() is that we can transform this QKP problem to another IP problem
z = cp.Variable((n,n),boolean=True)
q = b.diagonal()
b=np.zeros((10,10))
b[0][0]=q[0]
b[1][1]=q[1]
b[2][2]=q[2]
b[3][3]=q[3]
b[4][4]=q[4]
b[5][5]=q[5]
b[6][6]=q[6]
b[7][7]=q[7]
b[8][8]=q[8]
b[9][9]=q[9]
x = cp.Variable(n,boolean=True)

#obj = cp.Maximize(v@x+q[0]*z[0][0]+q[1]*z[1][1]+q[2]*z[2][2]+q[3]*z[3][3]+q[4]*z[4][4]+q[5]*z[5][5]+q[6]*z[6][6]+q[7]*z[7][7]+q[8]*z[8][8]+q[9]*z[9][9])
obj = cp.Maximize(v@x+cp.sum(b*z))

constraints = [
  w@x <= W, 
  #∑w[i]*z[i][j]<=(W-w[i])*x[j]
  w*z[:,0:1]-w[0]*x[0]<=(W-w[0])*x[0],
  w*z[:,1:2]-w[1]*x[1]<=(W-w[1])*x[1],
  w*z[:,2:3]-w[2]*x[2]<=(W-w[2])*x[2],
  w*z[:,3:4]-w[3]*x[3]<=(W-w[3])*x[3],                  
  w*z[:,4:5]-w[4]*x[4]<=(W-w[4])*x[4],                                 
  w*z[:,5:6]-w[5]*x[5]<=(W-w[5])*x[5],
  w*z[:,6:7]-w[6]*x[6]<=(W-w[6])*x[6],
  w*z[:,7:8]-w[7]*x[7]<=(W-w[7])*x[7],
  w*z[:,8:9]-w[8]*x[8]<=(W-w[8])*x[8],
  w*z[:,9:10]-w[9]*x[9]<=(W-w[9])*x[9],
  #0<=z[i][j]<=x[j]<=1,i!=j
  z[1:10,0:1]<=x[0],
  z[0:1,1:2]<=x[1],z[2:10,1:2]<=x[1],
  z[0:2,2:3]<=x[2],z[3:10,2:3]<=x[2],
  z[0:3,3:4]<=x[3],z[4:10,3:4]<=x[3],
  z[0:4,4:5]<=x[4],z[5:10,4:5]<=x[4],
  z[0:5,5:6]<=x[5],z[6:10,5:6]<=x[5],
  z[0:6,6:7]<=x[6],z[7:10,6:7]<=x[6],
  z[0:7,7:8]<=x[7],z[8:10,7:8]<=x[7],
  z[0:8,8:9]<=x[8],z[9:10,8:9]<=x[8],
  z[0:9,9:10]<=x[9],
  #z[0]==cp.transforms(z[:,0:1]) 
  #z[i][j]=z[j][i]
  z[0][1]==z[1][0],z[0][2]==z[2][0],z[0][3]==z[3][0],z[0][4]==z[4][0],z[0][5]==z[5][0],z[0][6]==z[6][0],z[0][7]==z[7][0],z[0][8]==z[8][0],z[0][9]==z[9][0],
  z[1][2]==z[2][1],z[1][3]==z[3][1],z[1][4]==z[4][1],z[1][5]==z[5][1],z[1][6]==z[6][1],z[1][7]==z[7][1],z[1][8]==z[8][1],z[1][9]==z[9][1],
  z[2][3]==z[3][2],z[2][4]==z[4][2],z[2][5]==z[5][2],z[2][6]==z[6][2],z[2][7]==z[7][2],z[2][8]==z[8][2],z[2][9]==z[9][2],
  z[3][4]==z[4][3],z[3][5]==z[5][3],z[3][6]==z[6][3],z[3][7]==z[7][3],z[3][8]==z[8][3],z[3][9]==z[9][3],
  z[4][5]==z[5][4],z[4][6]==z[6][4],z[4][7]==z[7][4],z[4][8]==z[8][4],z[4][9]==z[9][4],
  z[5][6]==z[6][5],z[5][7]==z[7][5],z[5][8]==z[8][5],z[5][9]==z[9][5],
  z[6][7]==z[7][6],z[6][8]==z[8][6],z[6][9]==z[9][6], 
  z[7][8]==z[8][7],z[7][9]==z[9][7],   
  z[8][9]==z[9][8],                                                                        
               ]
int_prob = cp.Problem(obj,constraints) 
int_prob.solve()

if (int_prob.status == "optimal"):
    print('int_prob = ' + str(int_prob.value))
    print('x = ' + str(x.value))
    print('z = ' + str(z.value))

int_prob = 159.0
x = [1. 1. 1. 1. 0. 1. 0. 1. 1. 1.]
z = [[1. 1. 1. 1. 0. 1. 0. 1. 1. 1.]
 [1. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [1. 1. 1. 1. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 1. 1. 1. 0. 1. 0. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
